### PR TITLE
Testing - nosetests, tox, and Travis CI

### PR DESCRIPTION
**Pull request by msabramo**
There don't seem to be any tests (unless I missed them), but maybe this will inspire some test writing.

### CODE REVIEW

**Comment by progrium** [comment]
Yes, this is great. Although how is tox used? I know Travis CI, but what is tox and is it necessary? (I couldn't really get a feel for how it's useful from their website unfortunately)

**Comment by msabramo** [comment]
If you have a `tox.ini` and you have `pip install`ed tox, you run `tox` and it will test in various envs (python 2.6, python 2.7, python 3.2, pypy, jython, etc.). Similar in purpose to Travis, except that it runs in your working directory, so you can run it on unpushed or uncommitted code so you can find errors before breaking the Travis run. 

Here's what it looks like:

```
~/dev/git-repos/ginkgo$ tox
__________________________________ [tox sdist] __________________________________
[TOX] ***creating sdist package
[TOX] /Users/marca/dev/git-repos/ginkgo$ /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python setup.py sdist --formats=zip --dist-dir .tox/dist >.tox/log/0.log
[TOX] ***copying new sdistfile to '/Users/marca/.tox/distshare/Ginkgo-0.5.0dev.zip'
______________________________ [tox testenv:py26] _______________________________
[TOX] ***reusing existing matching virtualenv py26
[TOX] ***upgrade-installing sdist
[TOX] /Users/marca/dev/git-repos/ginkgo/.tox/py26/log$ ../bin/pip install --download-cache=/Users/marca/dev/git-repos/ginkgo/.tox/_download /Users/marca/dev/git-repos/ginkgo/.tox/dist/Ginkgo-0.5.0dev.zip -U --no-deps >8.log
[TOX] /Users/marca/dev/git-repos/ginkgo$ .tox/py26/bin/nosetests

----------------------------------------------------------------------
Ran 0 tests in 0.016s

OK
______________________________ [tox testenv:py27] _______________________________
[TOX] ***reusing existing matching virtualenv py27
[TOX] ***upgrade-installing sdist
[TOX] /Users/marca/dev/git-repos/ginkgo/.tox/py27/log$ ../bin/pip install --download-cache=/Users/marca/dev/git-repos/ginkgo/.tox/_download /Users/marca/dev/git-repos/ginkgo/.tox/dist/Ginkgo-0.5.0dev.zip -U --no-deps >3.log
[TOX] /Users/marca/dev/git-repos/ginkgo$ .tox/py27/bin/nosetests

----------------------------------------------------------------------
Ran 0 tests in 0.015s

OK
_________________________________ [tox summary] _________________________________
[TOX] py26: commands succeeded
[TOX] py27: commands succeeded
[TOX] congratulations :)
```

**Comment by msabramo** [comment]
Where tox is super useful I think is when working on Python 3 compatibility, because that for me always involves a ton of trial and error and lots of iterations to get it right. Maybe not an issue for Ginkgo (does gevent work on Python 3?)

**Comment by progrium** [comment]
I believe there is a branch of gevent that is working in Python 3. Nevertheless, Ginkgo is potentially not gevent-specific, so we should probably be thinking about Python 3.

**Comment by kyleconroy** [comment]
@msabramo Looks like Python 3 compatibility is a separate issue to discuss. However, this test stuff is great, thanks for the pull request

**Pull request merged**
