### PR TITLE
Recreation of https://github.com/progrium/gservice/pull/9

### PR DESCRIPTION
**Pull request by objcode**
https://github.com/progrium/gservice/pull/9

### CODE REVIEW

**Comment by objcode** [comment]
Alright, once this pull request merges I'll finish cleaning up my gevent-tools fork rename.

**Comment by objcode** [comment]
If you can merge this in tomorrow I would be much obliged.  Trying to get python framework out the door and it currently needs a bumped gservice version.

**Comment by progrium** [comment]
Was this recreated yet?

On Thu, Sep 29, 2011 at 1:53 AM, Sean McQuillan
reply@reply.github.com
wrote:

> https://github.com/progrium/gservice/pull/9
> 
> You can merge this Pull Request by running:
> 
>  git pull https://github.com/smcq/gevent-tools master
> 
> Or you can view, comment on it, or merge it online at:
> 
>  https://github.com/progrium/gservice/pull/10
> 
> -- Commit Summary --
> - strictly don't allow gevent to be imported before run kicks off.
> - Merge branch 'master' of https://github.com/progrium/gevent-tools
> - allow for named global services by creating a service generator instead of a service function.
> - don't restop/restart children.  We should consider moving this to use an explicit state machine object if this grows more complex transitions.
> - docs typo
> - Merge ../progrium/gservice
> - move globalservice to finish move.
> - Finish rename for globalservice.
> 
> -- File Changes --
> 
> M gservice/core.py (58)
> A gservice/globalservice.py (40)
> M gservice/runner.py (55)
> M gservice/tests/test_runner.py (189)
> M gservice/tests/test_service.py (25)
> 
> -- Patch Links --
> 
>  https://github.com/progrium/gservice/pull/10.patch
>  https://github.com/progrium/gservice/pull/10.diff
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/progrium/gservice/pull/10

## 

Jeff Lindsay
http://progrium.com

**Comment by objcode** [comment]
Was what recreated?

**Comment by progrium** [comment]
Oh. This pull request. I was confused and thought I was replying to the old one. Or whatever.

**Pull request merged**
