### PR TITLE
Various changes discussed in person

### PR DESCRIPTION
**Pull request by objcode**
- Add a globalservice that manages the user defined main service
- Add global named services that are siblings of the main service, for example db connection pools
- Change start/stop to not restart/restop children
- Allow lookup of global named services by using Service('name')
- Allow registration of global named services by using Service(name='name', service=service, register=True)
- Abort if gevent is imported by the config file.
- Enforce ordering of child services
- Stop child services in reverse order

### CODE REVIEW

**Comment by progrium** [comment]
I like lookup of global services with Service('name'), but registration doesn't make as much sense. I'd prefer a class method like Service.register('name', service).

**Comment by progrium** [comment]
And maybe we can encapsulate the lookup logic in a lookup class method that's called in **new** ...

**Comment by objcode** [comment]
Doing both services refactor now, apparently the pull request is still active

**Comment by objcode** [comment]
I'm going to delete this pull request and make a new one.  It's borking updating the pull request.

**Pull request closed without merging**
