### PR TITLE
refactor config

### PR DESCRIPTION
**Pull request by inconshreveable**

### CODE REVIEW

**Comment by progrium** [comment]
I think I like everything in here _except_ the new way you work with Setting and also making each member of Configuration module level. An alternative proposal is to do what I've started here:
https://github.com/progrium/ginkgo/blob/ginkgo/ginkgo/__init__.py

The ginkgo module would contain a settings var that points to the default configuration. This way you get a similar module-level-like interface, but without specifying each member. This is important so that it can change. For example, process will be another ginkgo module variable/global. It represents the top level service so you can always reference it with ginkgo.process .. however, instead of thread-locals, I've decide to make process a special context manager that will change the globals. So given some process object, you can say `with process` and inside of that ginkgo.process will be that process and ginkgo.settings will be the config associated with that process. 

So you'd interact with configuration with settings.get, settings.set, etc. 

However, I don't like the descriptor factory, but I see why you like it. Perhaps a compromise is to have a ginkgo.Setting alias to ginkgo.settings.setting

Thoughts?

**Comment by progrium** [comment]
I was going to pull and then integrate my changes above for you to review, but since I pushed I can't pull yours automatically now. Would you mind pulling from me and re-pushing so I can pull it in?

**Comment by inconshreveable** [comment]
I dislike the solution being "the ginkgo framework takes care of it for you by creating a global 'settings' variable" because the config module should be just as easy to use and accessible as a standalone toolkit. In fact, it might be nice to package the config stuff separately as I think it's really useful even outside of the ginkgo framework.

**Comment by progrium** [comment]
This solution doesn't preclude it being used independently. You'd just have to manage your own singleton, which I think is fair. In fact, we can even drop _default_config from the module. That's way more toolkit-y than forcing it to come with its own singleton.

**Pull request merged**
